### SEND
POST http://localhost:8080/api/enviar
Content-Type: application/json

"{{$datetime iso8601}} testeeeEeEEeEEEeEeEEeEEeeeEEEEEE"



### RECEIVE
GET http://localhost:8080/api/receber
Content-Type: application/json


